import type { Metadata } from 'next';
import { Nav, Footer } from '@/components';

import '@/styles/fonts.scss';
import '@/styles/reset.scss';
import '@/styles/variables.scss';
import '@/styles/media.scss';
import '@/styles/grid.scss';
import '@/styles/globals.scss';
import '@/styles/common.scss';

export const metadata: Metadata = {
  title: 'AutoChina',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
